# Netlify configuration file

[build]
  # Directory to change to before starting a build.
  base = "frontend"

  # The command to build your site
  command = "npm run build"

  # The directory to publish (relative to the base directory)
  publish = "dist"

# Redirect and rewrite rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
